### ISSUE TITLE
Some markdown command not executed properly - ##title

### ISSUE THREAD

**Issue by GeReinhart** [KelkooGroup/theGardener#224]
http://dc1-thegardener-dev-srv-01.dev.dc1.kelkoo.net:9000/app/documentation/navigate/_public;path=theGardener%3Emaster%3E%2F/theTeaser
![image](https://user-images.githubusercontent.com/5529106/64111254-8313c980-cd84-11e9-9580-481e8bcfd0d8.png)

**Comment by loriepisicchio** [comment]
Not a bug. Actually it's just the mardown itself is not correct.
