### ISSUE TITLE
Some pages not properly displayed

### ISSUE THREAD

**Issue by GeReinhart** [KelkooGroup/theGardener#239]
For instance when there are several times the  code

```thegardener
{
}
```
Example 1 :

http://gitlab.corp.kelkoo.net/syndication/shoppingApi/blob/qa/documentation/Public/Guides/signUrlGuide.md
![image](https://user-images.githubusercontent.com/5529106/64257306-6e226c00-cf25-11e9-9e27-4409a5c948db.png)

Only the end of the page visible

Example 2 :
http://gitlab.corp.kelkoo.net/syndication/shoppingApi/blob/qa/documentation/Public/Guides/requestBuilder.md

![image](https://user-images.githubusercontent.com/5529106/64257342-809ca580-cf25-11e9-8a14-1bc5fc61a19a.png)

The label of the page is not used on the tab, the Swagger is not displayed

**Comment by loriepisicchio** [comment]
This is due to a bug in the regex that clears thegardener metadata. Has to be fixed server side.
