### ISSUE TITLE
Relative internal links

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#342]
As a developer, I want to be able to create internal links betweens the pages I write without having to put the full path every time. That is I want **relative** internal links.

Depends on: https://github.com/KelkooGroup/theGardener/issues/70

### Scenario

Given a files hierarchy like this:
```
doc/public/features/overview.md
doc/public/features/architecture.md
doc/public/features/featureA/details.md
```
I want to be able to make a link from _overview.md_ to _architecture.md_ with following syntax:
```[mylink](thegardener://path=./architecture.md)```
And I want to be able to make a link from _overview.md_ to _details.md_ with following syntax:
```[mylink](thegardener://path=./featureA/details.md)```

**NB:** syntax of the link is open to discussion but I think the `./` is universal and easy to understand

### From a user POV

As a end user of the documentation, when I click on such link it should:
- not reload the full page, it should be smooth, the same way we change from a tab to another
- open the menu to the right hierarchy
- display the page
- change the url in the browser match the new page
(same as for non relative internal links)

Variables should also be possible to use in relative links.

**Comment by gaeljw** [comment]
@GeReinhart I created this story, feel free to tell me if you think it's not correctly described

**Comment by GeReinhart** [comment]
@gaeljw it's perfect. thanks

**Comment by gaeljw** [comment]
IMHO We should not even have `path=` or `relativepath=`, it should be `thegardener://<pathRelativeOrNot>`
But there is something about `navigate` from I've seen to navigate to another project?

As a developer I would expect something close to what a standard URI looks like.
It could be `thegardener://project@path` if we need the have 2 infos in the link (project + path). And without a project it means current project.

But I don't have all the features in mind and this is only my developer POV.
