### ISSUE TITLE
Mobile compatible

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#359]
When browsing the documentation of theGardener itself on mobile, it's almost impossible to view any content.
See screenshot below.

I believe we should have a mobile compatible presentation. Not necessarily with all features but a minimal working UI.

![Screenshot_20191031-103505_Firefox](https://user-images.githubusercontent.com/18280708/67935750-d199e480-fbca-11e9-83af-2fb0250c4aff.jpg)

**Comment by ojacques** [comment]
I was... almost ready to get started with theGardener following the talk at snowcamp. I could not even see / read the doc because of this. Deal breaker to say the least.
Hope this issue gets updated so that I can consider theGardener again. Keep it up! 👍🏻

**Comment by GeReinhart** [comment]
I understand. We will work on it. Saying that we focus on a presentation on a large screen : the main UC is I'm on the office on my desktop to do some DEV or Specification an I need some documentation... so I'm on a big screen.
Thanks for the comment.

**Comment by GeReinhart** [comment]
First draft for the mobile version of theGardener: https://xd.adobe.com/view/2bec58e8-17bf-4779-714f-cab954b89d1c-5ddd/ . It's a mock.

**Comment by GeReinhart** [comment]
About to be released and packed in docker

**Comment by GeReinhart** [comment]
Ping  @ojacques
