### ISSUE TITLE
[UI] Better display the chosen branch

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#36]
On the Criterias module, when selecting a project, the dropdown to choose a Git branch is too small, almost not noticeable.
And the default value displays "s..." without knowing what branch it will use.

See screenshot below:
![2018-11-26_17-19](https://user-images.githubusercontent.com/18280708/49027170-e04c7000-f19f-11e8-80e4-776bc582851c.png)

**Comment by GeReinhart** [comment]
Solved
