### ISSUE TITLE
Provide a packaged version with Docker

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#431]
To be defined more precisely but the main idea is to provide an easy way to run theGardener without having to install sbt, build it...

It will probably end up with a Dockerfile and/or a public Docker image.

Tasks:
- [x] Create a Docker Hub organization
- [x] Minimal docker image to run theGardener with embedded conf/database
- [x] Build the image with sbt
- [x] Publish the image with sbt to Docker Hub
- [x] Be able to load custom configuration
- [x] Be able to configure a remote database (MySQL)
- [x] Be able to load sample data (theGardener doc itself)
- [x] Document different ways of running the image
- [x] Document build/push image
- [ ] Configure auto builds on Docker Hub or Github actions / Document it

**Comment by gaeljw** [comment]
As you may have guessed, I wrote this issue to remind myself to work on it :D

**Comment by gaeljw** [comment]
A first draft is visible in the PR #450. And a first version of the Docker image has been pushed and is visible at https://hub.docker.com/r/kelkoogroup/thegardener.

But for now, the image cannot be used because it only contains the Play application and not the Angular one.

I started with the idea that it would be easier to manage all the app lifecycle with sbt, thus I added the docker image creation as a sbt task.
Either:
- we continue this way and add the Angular packaging as part of the sbt lifecycle (ideally as part of the `sbt stage`, we can get inspiration at https://github.com/yohangz/scala-play-angular-seed).
- Or we don't want to do that and we can have a proper Dockerfile which will build the Angular app, then the Play app, and finally package the whole.
Both options can make sense but the first would be way faster I believe.

Any thought @GeReinhart or @notflorian ? :)

**Comment by gaeljw** [comment]
Note to myself: try to use the JIB plugin (sbt version => https://ilhicas.com/2019/04/23/Play-Framework-Docker-jib-sbt.html)

**Comment by GeReinhart** [comment]
I don't really understand the difference, sorry. 
As PO, my points are : 
  - it should be dead easy for the user do test the application with a minimum settings that show theGardener itself registered project
  - if it's complicated to create a new image it's not an issue for me as long as it is well documented
  - you can rely on https://github.com/KelkooGroup/theGardener/tree/v0.12.0 

@gaeljw Do you think you will be able to build one for the SnowCamp ?

**Comment by gaeljw** [comment]
Yes, no problem to have it ready for SnowCamp. Actually I already published an image on the Docket Hub.

The only thing not working is the Angular part because of some routing issues but it's not related to Docker. Maybe something is broken on the version I used to create the image.. we can have a look together @GeReinhart ;)
