### ISSUE TITLE
Unable to include cucumber scenario

### ISSUE THREAD

**Issue by torito** [KelkooGroup/theGardener#433]
I include an scenario in the following way

```thegardener
{
  "scenarios" : 
     {
        "feature": "/LeadService/checkLeadServiceUrl.feature",
        "select": { "tags" : ["@documentation_valid"]  }
     }
}
```
And an error appears in the console, and the scenario is not rendered correctly
It could be related to the scenario itself, that is described as follow:
```
  @nominal_case @level_1_specification @valid @documentation_valid
  Scenario Outline: check the parameter value
    Given the value "3<value>"
    When I check the value
    Then the check result is "true"
    Examples:
      | value |
      | 5     |
```

**Comment by GeReinhart** [comment]
See http://thegardener.corp.kelkoo.net/app/documentation/navigate/_publisher;path=kelkooUrl%3Efeature_the-gardner-style-doc%3E_features_/SignatureChecks
