### ISSUE TITLE
Scroll to top when clicking on some buttons inside a page

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#481]
Given a documentation page with a BDD scenario included, containing a Then step with JSON data.
When I click on the JSON to collapse/expand it
Then the page automatically scrolls to the top

The page should not scroll at all.

Example:
![image](https://user-images.githubusercontent.com/18280708/71989244-97376e00-3231-11ea-80c8-97282b361d42.png)

**Comment by lecunm** [comment]
Duplicate of #514
