### ISSUE TITLE
Spinner when page loads

### ISSUE THREAD

**Issue by gaeljw** [KelkooGroup/theGardener#596]
I noticed few times that for fresh pages (not yet in cache?), you can navigate to the page, the menu is updated but the content is not.

There should be a spinner or something to show that content is loading.

Screenshot:
![image](https://user-images.githubusercontent.com/18280708/76549555-f3687980-6490-11ea-8e9c-f4384fd225b5.png)

**Comment by GeReinhart** [comment]
Agree. 
More over, we should check the cache system: all pages should be pre computed ans in the cache

**Comment by GeReinhart** [comment]
It was due to a problem on server side. All pages should be on cache. This is fixed on server side. So as consequence we won't display anything, yet, on the front.
