### ISSUE TITLE
Add a link to the source of the page.

### ISSUE THREAD

**Issue by GeReinhart** [KelkooGroup/theGardener#604]
On the project table add a field sourcePathTemplate

for instance :

http://gitlab.corp.kelkoo.net/syndication/publisherManagementWS/blob/${branch}/doc/${relativePath}

Replace ${branch} and ${relativePath} to display the link of the page in GitLab, GitHub...

Add link to the source page at the bottom of the page. "View source" button.

If the field sourcePathTemplate is not defined => do not show anything

**Comment by gaeljw** [comment]
We should probably add a conf to enable the display or not: on public instances of theGardener we don't want to expose a link to our Gitlab that won't work anyway.

**Comment by gaeljw** [comment]
I'm not sure we need an additional field `sourcePathTemplate`, it could be derived from the `repositoryUrl`.

As a user I would like to enter the minimum of conf :)
