### ISSUE TITLE
Display properly Scenario steps with XML

### ISSUE THREAD

**Issue by GeReinhart** [KelkooGroup/theGardener#606]
![image](https://user-images.githubusercontent.com/5529106/76878824-a95b0b80-6875-11ea-984a-2ce1a29dae21.png)

**Comment by gaeljw** [comment]
I didn't notice that this only applies to Scenarios steps.

Given the scenario is defined like this:
```
Then something
"""xml
<something />
"""
```
I think that the backend should keep the "xml" information and pass it to the frontend.

Then the frontend should just use prismjs with the proper `<code class="language-{{language-from-backend}}">`.

The tricky part is I'm not sure the "xml" info is preserved correctly.

**Comment by gaeljw** [comment]
I don't have enough knowledge on the project to create a PR but I believe the idea would be to modify this method in `FeatureService`:

```scala
private def mapGherkinSteps(gherkinSteps: JList[ast.Step]): Seq[Step] = {
    gherkinSteps.asScala.zipWithIndex.map {
      case (step, id) =>
        val argument = step.getArgument match {
          case dataTable: ast.DataTable =>
            dataTable.getRows.asScala.map(_.getCells.asScala.map(_.getValue))
          case tableRow: ast.TableRow =>
            Seq(tableRow.getCells.asScala.map(_.getValue))
          case docString: ast.DocString =>
            Seq(Seq(docString.getContent))
            // <--------- here use the docString.getContentType
          case _ => Seq()
        }

        Step(id.toLong, step.getKeyword.trim, step.getText, argument)
    }
  }
```

**Comment by gaeljw** [comment]
A first step without having fancy formatting would be to just preserve the linebreaks which are not preserved right now.
