### ISSUE TITLE
Internal link

### ISSUE THREAD

**Issue by GeReinhart** [KelkooGroup/theGardener#70]
Be able in any markdown file to make an internal link to a page in theGardener.

## Link under the same node : 

For instance, from a page under http://thegardener.corp.kelkoo.net be able to make a link to the page the page : https://thegardener.kelkoogroup.com/app/documentation/navigate/_doc;path=theGardener>master>_features_/administration
![image](https://user-images.githubusercontent.com/5529106/67370091-67ee5a80-f57a-11e9-8edb-49c90f014a53.png)

To make the life easier to the writer he will copy past the url from 'path=' to the end of the url and use it to make the link. with the following syntax :

Syntax of the link : thegardener://path={project.id with front encoding}>{branch.name with front encoding}>{directory.path with front encoding}/{page.name}#anchor

For instance : 
``` [internal link to administration of the project theGardener](thegardener://path=theGardener>master>_features_/administration) ```

## Link under another node : 

The writer he will copy past the url from 'navigate/' to the end of the url and use it to make the link. with the following syntax :

Syntax of the link : thegardener://navigate/{hierarchy path with front encoding};path={project.id with front encoding}>{branch.name with front encoding}>{directory.path with front encoding}/{page.name}#anchor

For instance : 
``` [internal link to another hierarchy ](thegardener://navigate/_publisher;path=publisherSystems>master>_Public_/publisherServices) ```

## When the user click on this link

 - the full page DO NOT RELOAD, it should be smooth, the same way we change from a tab to another 
- the menu is open to the right hierarchy
- the page is displayed
- the url in the browser is changed to match the new page

Note that the writer can use also the variables :
For instance : 
``` [internal link to administration of the project theGardener, using variables](thegardener://path=${project.current}>${branch.stable}>_features_/administration) ```
For Variables, see #63

**Comment by gaeljw** [comment]
Would be nice to be able to do relative links without having to put again the project ID, branch or even directory.

**Comment by GeReinhart** [comment]
@gaeljw We will start with this one, and iterate with relative path.... please write a story for that in the same spirit as this one ;) Thanks
